version: "3.8"

services:
  db:
    image: postgres:16.6-alpine3.21
    container_name: quest-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: quest
    volumes:
      - local_pgdata:/var/lib/postgresql/data
    networks:
      - service-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: quest-pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - service-network

volumes:
  local_pgdata:
  pgadmin-data:

networks:
  service-network:
    name: service-network